[package]
name = "debugger-core"
version = "0.1.0"
edition = "2024"
authors = ["Florian Hartung <florian.hartung5@gmail.com>", "Marek Freunscht <freunscht58@outlook.de>"]

[dependencies]
log.workspace = true